### ISSUE TITLE
[Service Issue] Perplexity: Bad Request (400): "error": { "message": "Invalid model 'llama-3-sonar-large-32k-online'.

### ISSUE THREAD

**Issue by veerababumanyam** [bhdicaire/visioStencils#3]
Perplexity is not working, getting the following error:
[Service Issue] Perplexity: Bad Request (400): "error": { "message": "Invalid model 'llama-3-sonar-large-32k-online'. Permitted models can be found in the documentation at https://docs.perplexity.ai/docs/model-cards.", "type": "invalid_model", "code": 400 } [DEV_URL: https://api.perplexity.ai/chat/completions]

**Comment by bhdicaire** [comment]
You probably made a mistake and published this issue on the wrong repository
